apiVersion: v1
kind: Service
metadata:
  name: registry-service
  namespace: docker-registry
spec:
  selector: 
   app: registry
  type: NodePort 
  ports:
  - port: 443
    nodePort: 31320
    protocol: TCP
    targetPort: 443  