# Deployment Docker Registry
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry
  namespace: docker-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      labels:
        app: registry
        name: registry
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
    spec:
      nodeSelector: 
        node-type: worker
      containers:
      - name: registry
        image: registry:2
        ports:
        - containerPort: 5000
        env:
        - name: REGISTRY_AUTH
          value: "htpasswd"
        - name: REGISTRY_AUTH_HTPASSWD_REALM
          value: "Registry Realm"
        - name: REGISTRY_AUTH_HTPASSWD_PATH
          value: "/auth/htpasswd"   
        - name: REGISTRY_HTTP_TLS_CERTIFICATE
          value: "/certs/tls.crt"
        - name: REGISTRY_HTTP_TLS_KEY
          value: "/certs/tls.key"
        volumeMounts:
        - name: registry-storage
          mountPath: "/var/lib/registry"
        - name: registry-certs
          mountPath: "/certs"
        - name: registry-auth
          mountPath: "/auth"      
      volumes:
        - name: registry-storage
          persistentVolumeClaim:
            claimName: docker-registry-pvc
        - name: registry-certs-secret
          secretName:
            secretName: docker-registry-tls-cert
        - name: registry-auth-secret
          secret:
            secretName: registry-auth-secret    

